# _config.yml
# Elige un tema de los soportados por GitHub Pages.
# 'jekyll-theme-minimal' es uno muy limpio y popular para empezar.
theme: jekyll-theme-minimal

# Título y descripción de tu sitio (aparecerá en la pestaña del navegador, etc.)
title: Rodrigo Jiménez - Software Developer
description: Resumeé
