# _config.yml
# Elige un tema de los soportados por GitHub Pages.
# 'jekyll-theme-minimal' es uno muy limpio y popular para empezar.
# https://pages.github.com/themes/
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

# Título y descripción de tu sitio (aparecerá en la pestaña del navegador, etc.)
title: Rodrigo Jiménez - Software Developer
description: Resume
