* Rodrigo Jiménez
** .Net Software Developer


*** Summary
    - More than 10 years of experience
    - Extensive domain of the .Net Framework
    - Object Oriented Programming
    - Functional Programming
    - JavaScript
    - Design Patterhs
    - Microservices
    - Containers
    - Virtualization
    - Networking
    - Windows/Linux advanced user
    - Multiplataform programmer using .net core
  
*** Technical skills
    
    | Languages             | C#, VisualBasic.Net, JavaScript, F#, Haskell, PHP |
    | Database              | Sql Server, Postgresql, Oracle, MySql             |
    | Web Servers           | IIS, Nodejs                                       |
    | Backend Frameworks    | .net, .net core, nodejs, haskell stack            |
    | Development Tools/Env | Visual Studio, VS Code, Linux/emacs/vim, Docker   |
    | Other                 | .net reactive, Signal R, F# Agents                |
    
*** Education
    Universidad de Guadalajara
    Bachelor's degree, Telecommunications Engineering


*** Certifications
    - Microsoft Certification Programming in HTML 5 with JavaScript and CSS 70-480

-----
* Professional Experience
  
** UL 9 years 3 months
Albany, New York Area
September 2015 - Present

*** Responsibilities:
- Implement, develop and maintain software solutions for chemical industry
- Share data with other companies at the industrial level using industry standards
- Help comapanies to achieve compliance on chemical regulations


*** Environment

a) Long running task engine.
This is a tool to run long running processes on multithreaded environment. 
I have been involved on developing interprocess communications system for this component.

Tech Stack
- Backend: C# TPL, SignalR, F# Agents.
- Database: Sql Server.

b) .Net MVC Software for capturing and processing Products containing chemical components.
Dynamically generated data entry wizard that depending on the user input calculates following 
fields according to the kind of material being registered. This software is sold on a subscripion
basis and handles user payments and lots of statistics and charts for user owned content.

Tech Stack
- Frontend: Knockout, TypeScript, JQuery, NPM, JSON.
- Backend: .Net MVC, XML, XSLT Transforms, REST Server, SOAP web services.
- Database: SQL Server.

c) ASP/ASP.Net Suite for regulation compliance.
This is a very complex and rich feature software for big customers handling lots of data. 
Data is intended to be shared keeping track of supply chain. Some of the areas i was involved in
include generation of labels that can be translated to more than 50 languages, publishing of 
regulatory documents, capturing of formulation for chemical products, etc.

Tech Stack:
- Frontend: JQuery, ASPX pages, JavaScript, MVC Pages
- Backend: .Net mix ASP/ASPNET connected to a .net background worker to handle long running multithreaded tasks.
- Database: SQL Server / Oracle / AWS

d) Other Projects.
Besides being part of big projects I have been comissioned to work on internal software tools
for management of clients, sells, estatistics. Mainly on .Net framework. 


** Quantuvis Consulting 1 year
California (via Softtek)
June 2009 - May 2010

*** Responsibilities:
- Migrate Java system to .Net
- Develop MVC.Net cross-compatible web page.
- Present valuable charts to our customers.


*** Environment

a) MVC .net System
MVC .Net cross-browser web page for companies that wanted to be compared
with their competitors so they can manage their milestones and achieve better
competitiveness in their areas.

Tech Stack
- Java
- Frontend: JQuery, JavaScript, JS Charts libraries. 
- Backend: C# MVC.
- Database: Sql Server.


** GMO 1 year 1 month
Boston city (via Softtek)
July 2008 - July 2009

*** Responsibilities:
- Create components using WPF for a windows app.
- Have high accuracy running code through unit testing.
- Present valuable charts to our customers.


*** Environment

a) WPF .net System
Rich client application, multithreaded, very user responsive, 
for a trading assets/shares software.

Tech Stack
- Frontend: AXML, WPF, Multithreading. 
- Backend: C#, WCF.
- Database: Sql Server.


** Vallarta Online 1 year
Puerto Vallarta Jalisco, Mexico.
July 2007 - June 2008

*** Responsibilities:
- Maitain existing web page for toursim.
- Make sure payments and booking of hotel/tour reservations work properly.
- Develope new modules for real state section.


*** Environment

a) ASP
Tourist oriented site on old ASP pages.

Tech Stack
- Asp
- Database: Sql Server.





